// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/get_location_use_case_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:geolocator/geolocator.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/domain/repositories/location_repository.dart'
    as _i2;
import 'package:weather_app/domain/usecases/get_location_usecase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocationRepository_0 extends _i1.SmartFake
    implements _i2.LocationRepository {
  _FakeLocationRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosition_1 extends _i1.SmartFake implements _i3.Position {
  _FakePosition_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetLocationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocationUseCase extends _i1.Mock
    implements _i4.GetLocationUseCase {
  MockGetLocationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocationRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLocationRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LocationRepository);

  @override
  _i5.Future<_i3.Position> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i5.Future<_i3.Position>.value(
              _FakePosition_1(this, Invocation.method(#execute, [])),
            ),
          )
          as _i5.Future<_i3.Position>);
}
